version: "2.4"

services:

  lpf-dev:
    image: dev-local-port-forwarding
    container_name: dev-local-port-forwarding
    build: .
    environment:
      - REMOTE_HOST=hostaneOrIp
      - REMOTE_PORT=81
    volumes:
      - $STACK_DIR/ssh:/home/code28/.ssh
    ports:
      - 8180:8180
